services:
  - type: web
    name: mathdata-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn FileData.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: FileData.settings
      - key: PYTHON_VERSION
        value: 3.11
